---
# Using cores=2 memory=6GB disks=1 hbase=True
hadoop_yarn_scheduler_minimum_allocation_mb: 1024
hadoop_yarn_scheduler_maximum_allocation_mb: 3072
hadoop_yarn_nodemanager_resource_memory_mb: 3072

hadoop_mapreduce_map_memory_mb: 512
hadoop_mapreduce_map_java_opts: '-Xmx409m'
hadoop_mapreduce_reduce_memory_mb: '1024'
hadoop_mapreduce_reduce_java_opts: '-Xmx819m' 
hadoop_yarn_app_mapreduce_am_resource_mb: 512
hadoop_yarn_app_mapreduce_am_command_opts: '-Xmx409m'
hadoop_mapreduce_task_io_sort_mb: 204