---
# - name: Pre-install
#   hosts: all
#   remote_user: root
#   sudo: yes
#   
#   roles:
#    - base_role

- name: Install Hadoop
  remote_user: root
  sudo: yes
  vars: 
   - java_version_major: 8
   - java_version_minor: 91
   - java_home: "/opt/java"
  hosts: 
   - hadoop_master
   - hadoop_slaves
  roles:
   - hadoop
