---
####### HBase #########
  hbase_version: '1.0.3'
  hbase_home: /opt/hbase
  hbase_root_dir: "hdfs://{{ groups['hadoop_namenodes'][0] }}:9000/hbase"
  hbase_home_full: '{{ hbase_home}}/hbase-{{hbase_version}}' 
  hbase_archive_file_force_copy: 'no'
  hbase_zookeeper_data_dir: /opt/hbase/zookeeper/