---
####### Hadoop #######
  hadoop_version: '2.6.0'
  hadoop_user: 'hadoop'
  hadoop_home: '/opt/hadoop'
  hadoop_data_dir: '/opt/hadoop/datadir'
  hadoop_name_dir: '/opt/hadoop/namedir'
  hadoop_archive_file_force_copy: 'no'

  hadoop_yarn_scheduler_minimum_allocation_mb: 1024
  hadoop_yarn_scheduler_maximum_allocation_mb: 8192
  hadoop_yarn_nodemanager_resource_memory_mb: 8192

  hadoop_mapreduce_map_memory_mb: 1024
  hadoop_mapreduce_map_java_opts: ''
  hadoop_mapreduce_reduce_memory_mb: 1024
  hadoop_mapreduce_reduce_java_opts: '' 
  hadoop_yarn_app_mapreduce_am_resource_mb: 1536
  hadoop_yarn_app_mapreduce_am_command_opts: -Xmx1024m
  hadoop_mapreduce_task_io_sort_mb: 100