---
- name: "Create hbase_home directory"
  file: path={{ hbase_home }} state=directory

- name: "Check HBase archive file"
  stat: path=/tmp/hbase-{{ hbase_version }}-bin.tar.gz
  register: hbase_archive_file

- name: "Check hbase_home exist"
  stat: path={{ hbase_home_full }}
  register: hbase_home_full_exist

- name: "Copy HBase installer"
  copy: src=hbase-{{ hbase_version }}-bin.tar.gz dest=/tmp/hbase-{{ hbase_version }}-bin.tar.gz force={{ hbase_archive_file_force_copy }}
  when: (hbase_home_full_exist.stat.isdir is not defined) and (hbase_archive_file.stat.exists == False)

- name: "Unpack HBase"
  unarchive: src=/tmp/hbase-{{ hbase_version }}-bin.tar.gz dest={{ hbase_home }} copy=no
  when: hbase_home_full_exist.stat.isdir is not defined

- name: "Create HBase profile (env.)"
  template: src=hbase_profile.sh dest=/etc/profile.d/hbase.sh

- name: "Generate configs"
  template: src={{ item }} dest={{ hbase_home_full }}/conf/{{ item }}
  with_items:
    - hbase-site.xml
    - hbase-env.sh
    - regionservers

- name: "Set {{ hadoop_user }} as owner"
  file: path={{ hbase_home }} owner={{ hadoop_user }} recurse=yes