---
- name: Copy ssh-key from master
  become_user: '{{ hadoop_user }}'
  shell: "cat ~/.ssh/id_rsa.pub"
  register: ssh_pulic_key_master_raw

- set_fact: ssh_pulic_key_master={{ ssh_pulic_key_master_raw.stdout }}

- name: Create data_dir if not exist
  file: path={{ hadoop_data_dir }} state=directory owner={{ hadoop_user }} recurse=yes

- name: Create name_dir if not exist
  file: path={{ hadoop_name_dir }} state=directory owner={{ hadoop_user }} recurse=yes

- name: "Generate configs"
  template: src={{ item }} dest={{ hadoop_home_full }}/etc/hadoop/{{ item }} owner={{ hadoop_user }}
  with_items:
    - slaves
    - mapred-site.xml

# - debug: var=hostvars[inventory_hostname] verbosity=4