- name: Check JDK archive file 
  stat: path=/tmp/jdk-{{ java_version }}-linux-x64.gz
  register: java_archive_file

- name: Check java_home_full exist
  stat: path={{ java_home_full }}/bin/java
  register: java_bin_exist

- name: Copy JDK archive to node
  copy: src=jdk-{{ java_version }}-linux-x64.gz dest=/tmp/jdk-{{ java_version }}-linux-x64.gz force={{ java_archive_file_force_copy }}
  when: (java_bin_exist.stat.isreg is not defined) and (java_archive_file.stat.exists == False) 

- name: Ensures java_home dir exists
  file: path={{ java_home }} state=directory

- name: Unpack JDK
  unarchive: src=/tmp/jdk-{{ java_version }}-linux-x64.gz dest={{ java_home }} copy=no
  when: java_bin_exist.stat.isreg is not defined

- name: Correct java version selected
  alternatives: name={{ item.name }} link={{ item.link }} path={{ item.path }}
  when: java_bin_exist.stat.isreg is not defined
  with_items:
  - { name: java, link: /usr/bin/java, path: "{{ java_home_full }}/bin/java" }
  - { name: javac, link: /usr/bin/javac, path: "{{ java_home_full }}/bin/javac" }

- name: Create Java profile (env.)
  template: src=java_profile.sh dest=/etc/profile.d/java.sh